name: Generate Documentation

on:
  push:
    branches: [main]
    paths:
      - '**.tf'
      - 'README.md'

jobs:
  terraform-docs:
    name: Update Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1.4.1
        with:
          config-file: .terraform-docs.yml
          output-file: TERRAFORM_DOCS.md
          output-method: inject
          git-push: "true"